openapi: 3.1.1
info:
  title: Face Recognition API
  version: 1.0.0
  description:
tags:
  - name: Face
    description: Operation for register and validation face
paths:
  /face/register:
    post:
      tags:
        - Face
      summary: register new face
      description: Returns info of register face
      operationId: registerFace
      parameters:
        - name: subject
          in: query
          required: true
          description: identifier of subject
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                  description: The file of image (jpg, png)
            encoding:
              photo:
                contentType: image/png, image/jpeg
      responses:
        '201':
          description: Upload realized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FaceResponse'
        '413':
          description: The file is too large. The maximum limit is 2MB.
        '415':
          description: This media type is not supported. Please use only JPG or PNG.
        '400':
          description: Bad request
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal server error
components:
  schemas:
    FaceResponse:
      type: object
      properties:
        imageId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        subject:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-44665544654"
        createdAt:
          type: string
          format: date-time